# Makefile fragment: meant to be included by main Makefile
#  after defining some variables.

USER_OBJ=$(NAME).obj
PROGRAM=$(NAME).exe
NR_DEP=$(MAIN) lib/inc.h lib/inc.c lib/signals.c
NR=$(MAIN) 

sandrun: 
	- rm ../../../main.obj
	make main.obj
	cp main.obj ../../../main.obj

main.obj:
	@ ( [ -r ../../../main.obj ] && cp ../../../main.obj . ) || $(LINKER) $(LFLAGS) lib/main.cpp -c -o $@

